#+TITLE: apps.lua
#+PROPERTY: header-args :tangle apps.lua

Apps.org - the file that has everything to do with default apps per tag (or workspace), and changing your deafault browser.

This file is a org document that mirrors apps.lua to make it easier to understand and maintain. If you're in emacs, just use tangle to output the code blocks, no need to open up the lua!

* Table of contents :toc:
- [[#variables][Variables]]
- [[#action-apps][Action apps]]
- [[#tag-defaults][Tag defaults]]
- [[#startup-apps][Startup apps]]

* Variables
The important stuff that makes everything work properly.
#+BEGIN_SRC lua

local filesystem = require('gears.filesystem')
local with_dpi = require('beautiful').xresources.apply_dpi
local get_dpi = require('beautiful').xresources.get_dpi
local rofi_command = 'env /usr/bin/rofi -dpi ' .. get_dpi() .. ' -width ' .. with_dpi(400) .. ' -show drun -theme ' .. filesystem.get_configuration_dir() .. '/configuration/rofi.rasi -run-command "/bin/bash -c -i \'shopt -s expand_aliases; {cmd}\'"'
#+END_SRC

* Action apps
The apps that get used for diferrent actions and keybindings.
#+BEGIN_SRC lua

return {
  default = {
    screenshot = 'flameshot screen',
    screenshot_region = 'flameshot gui',
    terminal = 'terminator',
    rofi = rofi_command,
    lock = 'dm-tool lock',
    quake = 'terminator',
    email = 'mailspring',
    mail = 'mailspring',
#+END_SRC

* Tag defaults
The icons on the let sidebar are workspaces or "tags", when you click the plus sign on the top bar in a tag, it opens the default app listed here.
#+BEGIN_SRC lua
    browser = 'firefox-nightly',
    console = 'terminator',
    editor  = 'emacs',
    social = 'discord',
    game = rofi_command,
    files = 'nautilus',
    mail = 'mailspring',
    music = 'spotify'
  },
 #+END_SRC

* Startup apps
These apps run every time awesome is launched
#+BEGIN_SRC lua

  run_on_start_up = {
    'compton --config ' .. filesystem.get_configuration_dir() .. '/configuration/compton.conf',
    'nm-applet', -- wifi
    'blueberry-tray', -- Bluetooth tray icon
    'flameshot', -- Gotta screenshot
    'fluxgui', -- Blue light filter
    'xfce4-power-manager', -- Power manager
    'polychromatic-tray-applet', -- Razer Keyboards
    'pacwall -b "#192933" -d "#003F6B" -e "#EF6C00" -o ~/.config/awesome/theme/wallpapers/wallpaper.png', -- Wallpaper
    'slack -u', -- Slack Applet
    'mailspring -b', -- Email Applet
    '~/.config/awesome/configuration/awspawn' -- Script that kills "dirty" apps that linger on reload.
  }
}
#+END_SRC
